# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
#    parameter_name: value
    app.paginator.class: AppBundle\Utils\Pagination

services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]
    app.paginator:
        class: %app.paginator.class%
        arguments: ["@service_container"]
